In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
from pandas_profiling import ProfileReport

import matplotlib 
from matplotlib import pyplot as plt
from matplotlib import style
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

C:\Users\A803377\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

SystemError: initialization of _internal failed without raising an exception

In [24]:
# !pip install cloud-sql-python-connector[pytds]

In [25]:
from google.cloud.sql.connector import Connector
import sqlalchemy
import pytds

# initialize Connector object
connector = Connector()


conn = connector.connect
("10.27.10.7", 
"pytds",
user="svc_tableau_dev",
password="Onestream!@#",
db="TableauDB")

# fts.fast_to_sql(df,'rpt.ManualClearonInventory_Weekly',conn, if_exists="append", custom={'G/L acct':'nvarchar(225)','Plant':'nvarchar(225)','CoCd':'nvarchar(225)','Material':'nvarchar(225)','Month':'nvarchar(225)',
#                                                                                   'Year':'nvarchar(225)','Day':'nvarchar(225)','Material':'nvarchar(225)','Material Description':'nvarchar(225)','Unit':'nvarchar(225)',
#                                                                                          'Currency':'nvarchar(225)','Type':'nvarchar(225)','Total Value':'float','Total Stock':'float'}, temp=False)


connector.close()

SyntaxError: invalid syntax (Temp/ipykernel_4648/3277673216.py, line 12)

In [193]:
# import pandas as pd
# import glob

# # getting excel files from Directory Desktop
# path = r'C:\Users\A803377\OneDrive - Solenis LLC\Documents\Clearon Inventory Historical'

# # read all the files with extension .xlsx i.e. excel 
# filenames = glob.glob(path + "\*.xlsx")
# print('File names:', filenames)

# dfs = {}

# # for loop to iterate all excel files 
# # loop over the list of csv files
# for f in filenames:
    
#     # read the csv file
#     dfs[f.split("\\")[-1]] = pd.read_excel(f,sheet_name=2)
      
#     # print the location and filename
#     print('Location:', f)
#     print('File Name:', f.split("\\")[-1],'\n')

In [2]:
# # Reading Path of Latest Excel file 
# import glob
# import os.path

# folder_path = r'C:\Users\A803377\Clearon Inventory Historical'
# file_type = r'\*xlsx'
# files = glob.glob(folder_path + file_type)
# max_file = max(files, key=os.path.getctime)

# print(max_file)

In [3]:
# # df=pd.read_excel(r'C:\Users\A803377\Downloads\Inventory - 02.28.22.xlsx',sheet_name=2)

# # df=dfs[list(dfs)[10]].copy()
# df=pd.read_excel(max_file,sheet_name=2)


# df["Month"] = df["Month"].apply(lambda x: '{0:0>2}'.format(x))
# df["Plant"] = df["Plant"].apply(lambda x: '{0:0>4}'.format(x))
# df["Day"] = '30'
# df["CoCd"] = 'US33'

# # df['Reporting_Date'] = ((pd.Timestamp.today()- timedelta(days=8)).strftime('%Y-%m-%d')) 
# # df['Reporting_Date'] =  pd.to_datetime(df['Reporting_Date'], format='%Y-%m-%d')

# df[['G/L acct','Plant','CoCd', 'Month','Year','Day','Material', 'Material Description', 'Unit','Crcy','Type']] = df[['G/L acct','Plant','CoCd', 'Month','Year','Day','Material', 'Material Description', 'Unit','Crcy','Type']].astype('string')
# # Changing Naming Convention 
# df.rename(columns = {'    Total Value':'Total Value','Crcy':'Currency','   Total Stock':'Total Stock'}, inplace = True)

# df = df.replace(np.nan, '', regex=True)

# # df[['Total Stock','Total Value']] = df[['Total Stock','Total Value']].replace('', 0.0, regex=True)
# # df[['Total Stock','Total Value']] = df[['Total Stock','Total Value']].replace('-', 0.0, regex=True)
# # df[['Total Stock','Total Value']] = df[['Total Stock','Total Value']].astype('float64')
# df

In [16]:
# df.info()

In [17]:
# import pandas as pd
# import warnings
# warnings.filterwarnings("ignore")
# import urllib
# import sqlalchemy as sa
# import pyodbc
# import time
# from fast_to_sql import fast_to_sql as fts

# start = time.time()
# #Connecting to SQL 
# conn = pyodbc.connect("""
# DRIVER={SQL Server Native Client 11.0};
# SERVER= NAAZUREEDWS01;
# UID= svc_tableau_dev;
# PWD= EwSol@321$;
# DATABASE=TableauDB;
# trusted_connection=Yes""")

# fts.fast_to_sql(df,'rpt.ManualClearonInventory',conn, if_exists="append", custom={'G/L acct':'nvarchar(225)','Plant':'nvarchar(225)','Month':'nvarchar(225)','Year':'nvarchar(225)','Material':'nvarchar(225)','Material Description':'nvarchar(225)','Unit':'nvarchar(225)','Currency':'nvarchar(225)','Type':'nvarchar(225)'}, temp=False)

# conn.commit()
# conn.close()
# end = time.time()
# delta = end - start
# print("took %.2f seconds to process" % delta)
# print("Update Completed")

In [ ]:
[4:15 PM] Hari Babu Gorantla
EDWDBData.[rpt].[Manual_DeepDivePlantSpend_Costcenters_SGA] Deep

# Inventory weekly

In [4]:
# import pandas as pd
# import glob

# # getting excel files from Directory Desktop
# path = r'C:\Users\A803377\Clearon Inventory_Weekly'

# # read all the files with extension .xlsx i.e. excel 
# filenames = glob.glob(path + "\*.xlsx")
# print('File names:', filenames)

# dfs = {}

# # for loop to iterate all excel files 
# # loop over the list of csv files
# for f in filenames:
    
#     # read the csv file
#     dfs[f.split("\\")[-1]] = pd.read_excel(f)
      
#     # print the location and filename
#     print('Location:', f)
#     print('File Name:', f.split("\\")[-1],'\n')

In [2]:
df= pd.read_excel(r'C:\Users\A803377\Downloads\SQL Tables_Columns.xlsx',sheet_name=2,keep_default_na=False)
# df_oneStream= pd.read_csv(r'C:\Users\A803377\Downloads\Reporting_CubeData_2023M9.csv', keep_default_na=False)
df

,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION,DATA_TYPE
0,TableauDB,dbo,ManualEHSActionDatabaseFY21,Action Number,1,nvarchar
1,TableauDB,dbo,ManualEHSActionDatabaseFY21,Business Unit,2,nvarchar
2,TableauDB,dbo,ManualEHSActionDatabaseFY21,Area,3,nvarchar
3,TableauDB,dbo,ManualEHSActionDatabaseFY21,Offline Source,4,nvarchar
4,TableauDB,dbo,ManualEHSActionDatabaseFY21,Source,5,nvarchar
...,...,...,...,...,...,...
21763,TableauDB,test,testOpen Order,3rd party Purchase Order,91,nvarchar
21764,TableauDB,test,testOpen Order,3rd party Purchase Date,92,nvarchar
21765,TableauDB,test,testOpen Order,3rd party REFERDOC,93,nvarchar
21766,TableauDB,test,testOpen Order,3rd party Expected Ship Date,94,nchar
21767,TableauDB,test,testOpen Order,Logic,95,varchar

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21768 entries, 0 to 21767
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TABLE_CATALOG     21768 non-null  object
 1   TABLE_SCHEMA      21768 non-null  object
 2   TABLE_NAME        21768 non-null  object
 3   COLUMN_NAME       21764 non-null  object
 4   ORDINAL_POSITION  21768 non-null  int64
 5   DATA_TYPE         21768 non-null  object
dtypes: int64(1), object(5)
memory usage: 1020.5+ KB

In [7]:
df["TABLE_NAME"]= df["TABLE_NAME"].replace({'-':'_', '__':'_',' ':'_','$':'',
                                                                    '%':'per','#':'_no_',
                                                                   '+':'plus','<':'','>':'','$':'','@':'','!':'','=':''},regex=True)

error: nothing to repeat at position 0

In [8]:
df["TABLE_NAME"]= df["TABLE_NAME"].replace({'%':'per','#':'_no_', '+':'plus'},regex=True)

error: nothing to repeat at position 0

In [19]:
# Reading Path of Latest Excel file 
import glob
import os.path

folder_path = r'C:\Users\A803377\Clearon Inventory_Weekly'
file_type = r'\*xlsx'
files = glob.glob(folder_path + file_type)
max_file = max(files, key=os.path.getctime)

print(max_file)

C:\Users\A803377\Clearon Inventory_Weekly\Inventory Subledger 3_13_2023.xlsx

In [20]:
from datetime import timedelta

df=pd.read_excel(max_file)
# df=pd.read_excel(max_file,sheet_name=2)

# df=dfs[list(dfs)[0]].copy()
df[["CoCd",'ValA']] = df[["CoCd",'ValA']].astype(float).astype('string').replace('\.0', '', regex=True)
# df[['CoCd','Plant']] = df[['CoCd','Plant']].astype(float).astype('string').replace('\.0', '', regex=True)

df["CoCd"] = df["CoCd"].apply(lambda x: '{0:0>4}'.format(x))
df["ValA"] = df["ValA"].apply(lambda x: '{0:0>4}'.format(x))

df["Month"] = df["Month"].apply(lambda x: '{0:0>2}'.format(x))
df["Day"] = df["Day"].apply(lambda x: '{0:0>2}'.format(x))
df['CoCd'] = 'US33'
# df[["CoCd"]] = df[["CoCd"]].astype('string')
df[['G/L acct','ValA','CoCd', 'Month','Year','Day','Material', 'Material Description', 'Unit','Crcy','Type']] = df[['G/L acct','ValA','CoCd', 'Month','Year','Day','Material', 'Material Description', 'Unit','Crcy','Type']].astype('string')

df.rename(columns = {'   Total Stock':'Total Stock','Crcy':'Currency','    Total Value':'Total Value','ValA':'Plant'}, inplace = True)

# # df['Reporting_Date'] = (pd.Timestamp.today().strftime('%Y-%m-%d')) 

df['Reporting_Date'] = ((pd.Timestamp.today()- timedelta(days=1)).strftime('%Y-%m-%d')) 
df['Reporting_Date'] =  pd.to_datetime(df['Reporting_Date'], format='%Y-%m-%d')

df = df.replace(np.nan, '', regex=True)

df[['Total Stock','Total Value']] = df[['Total Stock','Total Value']].replace('', 0.0, regex=True)
df[['Total Stock','Total Value']] = df[['Total Stock','Total Value']].replace('-', 0.0, regex=True)
df[['Total Stock','Total Value']] = df[['Total Stock','Total Value']].astype('float64')

df

,G/L acct,Plant,CoCd,Day,Month,Year,Material,Material Description,Total Stock,Unit,Total Value,Currency,Type,Reporting_Date
0,131000,2700,US33,13,03,2023,32000120,UREA,20572.0,LB,7137.060000,USD,Raw Materials,2023-03-13
1,131000,2700,US33,13,03,2023,32000121,"CHLORINE, LIQUID",1346010.0,LB,756195.130000,USD,Raw Materials,2023-03-13
2,131000,2700,US33,13,03,2023,32000122,CAUSTIC SODA 50%,779993.0,LB,406076.650000,USD,Raw Materials,2023-03-13
3,131000,2700,US33,13,03,2023,32000123,SULFURIC ACID 93%,520529.0,LB,69178.610000,USD,Raw Materials,2023-03-13
4,131000,2700,US33,13,03,2023,32000124,SODIUM BISULFITE 40% SOLUTION,65012.0,LB,37306.073758,USD,Raw Materials,2023-03-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8515,134510,2700,US33,13,03,2023,CL9890,"HELICOIL REPAIR-KIT 7/16""-14",1.0,KIT,51.020000,USD,Other,2023-03-13
8516,134510,2700,US33,13,03,2023,CL990,BEARING MRC 5309,2.0,EA,82.620000,USD,Other,2023-03-13
8517,134510,2700,US33,13,03,2023,CL9900,"HELICOIL REPAIR-KIT 1/2""-13",1.0,KIT,71.280000,USD,Other,2023-03-13
8518,134510,2700,US33,13,03,2023,CL9910,"HELICOIL REPAIR-KIT 9/16""-12",1.0,KIT,0.000000,USD,Other,2023-03-13
8519,134510,2700,US33,13,03,2023,CL9930,"HELIC0IL REPAIR-KIT 3/4""-10",1.0,KIT,138.850000,USD,Other,2023-03-13

In [5]:
# df.columns

In [6]:
# print((pd.Timestamp.today()- timedelta(days=22)).strftime('%Y-%m-%d'))

In [7]:
# df.info()

# DRIVER={SQL Server Native Client 11.0};
# SERVER= NAAZUREEDWS01;
# UID= svc_tableau_dev;
# PWD= EwSol@321$;
# DATABASE=TableauDB;
# trusted_connection=Yes""")

In [21]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import urllib
import sqlalchemy as sa
import pyodbc
import time
from fast_to_sql import fast_to_sql as fts

start = time.time()
#Connecting to SQL 
conn = pyodbc.connect("""
DRIVER={SQL Server Native Client 11.0};
SERVER= 10.27.10.7;
UID= svc_tableau_dev;
PWD= Onestream!@#;
DATABASE=TableauDB;
trusted_connection=Yes""")

fts.fast_to_sql(df,'rpt.ManualClearonInventory_Weekly_test',conn, if_exists="append", custom={'G/L acct':'nvarchar(225)','Plant':'nvarchar(225)','CoCd':'nvarchar(225)','Material':'nvarchar(225)','Month':'nvarchar(225)',
                                                                                  'Year':'nvarchar(225)','Day':'nvarchar(225)','Material':'nvarchar(225)','Material Description':'nvarchar(225)','Unit':'nvarchar(225)',
                                                                                         'Currency':'nvarchar(225)','Type':'nvarchar(225)','Total Value':'float','Total Stock':'float'}, temp=False)

conn.commit()
conn.close()
end = time.time()
delta = end - start
print("took %.2f seconds to process" % delta)
print("Update Completed")
print(df['[Reporting_Date]'].unique())
print('Last File Uploaded :',max_file)

OperationalError: ('08001', '[08001] [Microsoft][SQL Server Native Client 11.0]Named Pipes Provider: Could not open a connection to SQL Server [53].  (53) (SQLDriverConnect); [08001] [Microsoft][SQL Server Native Client 11.0]Login timeout expired (0); [08001] [Microsoft][SQL Server Native Client 11.0]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (53)')

# Spent Report Historical

In [8]:
# import pandas as pd
# import glob

# # getting excel files from Directory Desktop
# path = r'C:\Users\A803377\Clearon Spend Weekly'

# # read all the files with extension .xlsx i.e. excel 
# filenames = glob.glob(path + "\*.xlsx")
# print('File names:', filenames)

# dfs = {}

# # for loop to iterate all excel files 
# # loop over the list of csv files
# for f in filenames:
    
#     # read the csv file
#     dfs[f.split("\\")[-1]] = pd.read_excel(f)  
      
#     # print the location and filename
#     print('Location:', f)
#     print('File Name:', f.split("\\")[-1],'\n')

In [9]:
# Reading Path of Latest Excel file 
import glob
import os.path

folder_path = r'C:\Users\A803377\Clearon Spend Weekly'
file_type = r'\*xlsx'
files = glob.glob(folder_path + file_type)
max_file = max(files, key=os.path.getctime)

print(max_file)

C:\Users\A803377\Clearon Spend Weekly\Spend Report 3_13_2023.xlsx

In [10]:
from datetime import timedelta

df=pd.read_excel(max_file)
# df=pd.read_excel(r'C:\Users\A803377\Clearon Spend Weekly\Spend Report 1_30_2023.xlsx',sheet_name=1)

# df=dfs[list(dfs)[8]].copy().fillna('')
# df[["CoCd"]] = df[["CoCd"]].astype(float).astype('string').replace('\.0', '', regex=True)
df[['Purchase Order', 'Vendor','Vendor Name','PO Item', 'Ship to Country','Ship to City', 'Ship to State','Del. Indicator','Material', 'Description', 'Material Group', 'Unit', 'Normalized Unit','Item Category', 'Acct Ass. Cat.', 'Incoterms', 'Invoice Payment Term','PO Payment Terms', 'Payment Term Name','Document Date(M/Y)', 'Invoice Receipt(M/Y)','Goods Received(M/Y)','Invoice Receipt Year','Goods Received Year','Vendor Mat. No','Invoice Reference']] = df[['Purchase Order', 'Vendor','Vendor Name','PO Item', 'Ship to Country','Ship to City', 'Ship to State','Del. Indicator','Material','Description', 'Material Group', 'Unit', 'Normalized Unit','Item Category', 'Acct Ass. Cat.', 'Incoterms', 'Invoice Payment Term','PO Payment Terms', 'Payment Term Name','Document Date(M/Y)', 'Invoice Receipt(M/Y)','Goods Received(M/Y)','Invoice Receipt Year','Goods Received Year','Vendor Mat. No','Invoice Reference']].astype('string').replace('\.0', '', regex=True)
df["Net Price"] = df["Net Price"].replace('', 0.0, regex=True)
df["Description"] = df["Description"].str.strip()
# df = df.replace(np.nan, '', regex=True)
df["Net Price"] = df["Net Price"].astype("float64")

df['Document Date'] = pd.to_datetime(df['Document Date'], format='%Y-%m-%d')
# df['Document Date'] = pd.to_datetime(df['Document Date']).dt.strftime('%Y-%m-%d')
# df['Reporting_Date'] = ((pd.Timestamp.today()- timedelta(days=1)).strftime('%Y-%m-%d')) 
df = df.replace(r"^ +| +$", r"", regex=True)
df = df.replace(np.nan, '', regex=True)
df.drop(df.tail(1).index,inplace=True) # drop last n rows

df.drop(["Invoice Reference"],axis= 1,inplace=True)

df

,Purchase Order,Vendor,Vendor Name,Ship to Country,Ship to City,Ship to State,PO Item,Del. Indicator,Material,Description,Material Group,Unit,Normalized Unit,Item Category,Acct Ass. Cat.,Incoterms,Invoice Payment Term,PO Payment Terms,Payment Term Name,Document Date,Document Date(M/Y),Invoice Receipt Year,Invoice Receipt(M/Y),Goods Received Year,Goods Received(M/Y),Vendor Mat. No,Order Qty,Normalized Order Qty,Net Price,Net Value,Freight Unit Price,Received Qty,Norm Received Qty,Received Amount,Invoice Amount,Norm Inv Unit Price
0,4500246477,1012267,STATE ELECTRIC SUPPLY COMPANY,US,CHARLOTTE,NC,10,,CL31380,TAPE ELEC PLASTIC 3/4,MRO05402,ROL,,0,,,,Z030,NET 30 DAYS,2022-10-01,10/2022,2022,10/2022,2022,10/2022,,20,20,7.46,149.20,0.0,20,20,149.20,149.20,7.46
1,4500246478,1013826,M-I LLC,US,DALLAS,TX,10,,CL82850,SPRING(16 EACH SCREENER),MRO05000,EA,,0,,,,Z060,"2% 10 Days, Net 60",2022-10-01,10/2022,2022,11/2022,2022,10/2022,,32,32,27.05,865.60,0.0,32,32,865.60,896.00,28.00
2,4500246479,1014413,Tabor Machine Company LLC,US,CHICAGO,IL,10,,CL78140,REPAIR EXHAUSTER HOFFMAN 38604-A,CAP00003,EA,,0,,,,Z040,NET 60 DAYS,2022-10-01,10/2022,2023,03/2023,2022,12/2022,,1,1,17109.0,17109.00,0.0,1,1,17109.00,17109.00,17109.00
3,4500246480,1018921,STATIONERS INC.,US,HUNTINGTON,WV,10,,CL30290,BAG PLASTIC 36 X 67 4-MIL,MRO05404,BOX,,0,,,,Z040,NET 60 DAYS,2022-10-01,10/2022,2022,12/2022,2022,10/2022,,6,6,120.29,721.74,0.0,6,6,721.74,721.74,120.29
4,4500246481,1000956,MRC GLOBAL,US,DALLAS,TX,10,,CL35600,"NIPPLE GALV 2"" CLOSE SCH 80",MRO04508,EA,,0,,,,Z040,NET 60 DAYS,2022-10-01,10/2022,2022,11/2022,2022,10/2022,,12,12,7.0,84.00,0.0,12,12,84.00,84.00,7.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4092,6000000213,1012117,NOVA RUBBER CO INC,US,SOUTH CHARLESTON,WV,30,,CL40400,VALVE 1/2 GATE BR 125 SCR 113G,MRO05612,EA,,0,,,,,,2023-03-08,03/2023,0,,0,,,0,0,0.0,0.00,0.0,0,0,0.00,0.00,0.00
4093,6000000213,1012117,NOVA RUBBER CO INC,US,SOUTH CHARLESTON,WV,40,,CL40420,VALVE 1/2 GATE 200#BR SCR,MRO05612,EA,,0,,,,,,2023-03-08,03/2023,0,,0,,,0,0,0.0,0.00,0.0,0,0,0.00,0.00,0.00
4094,6000000213,1012117,NOVA RUBBER CO INC,US,SOUTH CHARLESTON,WV,50,,CL41380,VALVE 2 GATE CI/BR-T 125 FLGD,MRO05612,EA,,0,,,,,,2023-03-08,03/2023,0,,0,,,0,0,0.0,0.00,0.0,0,0,0.00,0.00,0.00
4095,6000000213,1012117,NOVA RUBBER CO INC,US,SOUTH CHARLESTON,WV,60,,CL35340,NIPPLE 316SS 3/4 X 2 INCH SCH/80,MRO04500,EA,,0,,,,,,2023-03-08,03/2023,0,,0,,,0,0,0.0,0.00,0.0,0,0,0.00,0.00,0.00
4096,6000000213,1012117,NOVA RUBBER CO INC,US,SOUTH CHARLESTON,WV,70,,CL37080,"TEE INSTRUMENT 2""X1"" TFE LINED",MRO04504,EA,,0,,,,,,2023-03-08,03/2023,0,,0,,,0,0,0.0,0.00,0.0,0,0,0.00,0.00,0.00

In [75]:
# df.drop(["Description","Vendor Name","Payment Term Name"],axis= 1,inplace=True)
# df.drop(["Invoice Reference"],axis= 1,inplace=True)

# df["Description"].lenmax()
# df.astype(str).apply(lambda s: s.str.len()).max()

# print (df.Description.map(lambda x: len(x)).min())

In [11]:
# df['Net Value'].sum()

In [12]:
# df.info()

In [11]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import urllib
import sqlalchemy as sa
import pyodbc
import time
from fast_to_sql import fast_to_sql as fts

start = time.time()
#Connecting to SQL 
conn = pyodbc.connect("""
DRIVER={SQL Server Native Client 11.0};
SERVER= NAAZUREEDWS01;
UID= svc_tableau_dev;
PWD= EwSol@321$;
DATABASE=PricingHUBDB;
trusted_connection=Yes""")
                      

# fts.fast_to_sql( df,'rpt.ManualClearonSpendReport',conn, if_exists="append",custom={'Purchase Order':'nvarchar(225)','Vendor':'nvarchar(225)','Ship to Country':'nvarchar(225)','Ship to City':'nvarchar(225)','Ship to State':'nvarchar(225)','Del. Indicator':'nvarchar(225)','PO Item':'nvarchar(225)','Material':'nvarchar(225)','Material Group':'nvarchar(225)',
#                                                                             'Unit':'nvarchar(225)','Normalized Unit':'nvarchar(225)','Item Category':'nvarchar(225)','Acct Ass. Cat.':'nvarchar(225)','Incoterms':'nvarchar(225)','Invoice Payment Term':'nvarchar(225)','PO Payment Terms':'nvarchar(225)','Document Date(M/Y)':'nvarchar(225)','Invoice Receipt Year':'nvarchar(225)',
#                                                                               'Invoice Receipt(M/Y)':'nvarchar(225)','Goods Received Year':'nvarchar(225)','Goods Received(M/Y)':'nvarchar(225)','Vendor Mat. No':'nvarchar(225)',"Document Date":'datetime2(7)','Order Qty':'float', 'Normalized Order Qty':'float', 'Net Price':'float', 'Net Value':'float',
#                                                                                 'Freight Unit Price':'float', 'Received Qty':'float', 'Norm Received Qty':'float','Received Amount':'float', 'Invoice Amount':'float', 'Norm Inv Unit Price':'float'}, temp=False)
                                                                      
fts.fast_to_sql( df,'rpt.ManualClearonSpendReport_Weekly',conn, if_exists="replace",custom={'Purchase Order':'nvarchar(225)','Vendor':'nvarchar(225)','Ship to Country':'nvarchar(225)','Ship to City':'nvarchar(225)','Ship to State':'nvarchar(225)','Del. Indicator':'nvarchar(225)','PO Item':'nvarchar(225)','Material':'nvarchar(225)','Material Group':'nvarchar(225)',
                                                                            'Unit':'nvarchar(225)','Normalized Unit':'nvarchar(225)','Item Category':'nvarchar(225)','Acct Ass. Cat.':'nvarchar(225)','Incoterms':'nvarchar(225)','Invoice Payment Term':'nvarchar(225)','PO Payment Terms':'nvarchar(225)','Document Date(M/Y)':'nvarchar(225)','Invoice Receipt Year':'nvarchar(225)',
                                                                              'Invoice Receipt(M/Y)':'nvarchar(225)','Goods Received Year':'nvarchar(225)','Goods Received(M/Y)':'nvarchar(225)','Vendor Mat. No':'nvarchar(225)',"Document Date":'datetime2(7)','Order Qty':'float', 'Normalized Order Qty':'float', 'Net Price':'float', 'Net Value':'float',
                                                                                'Freight Unit Price':'float', 'Received Qty':'float', 'Norm Received Qty':'float','Received Amount':'float', 'Invoice Amount':'float', 'Norm Inv Unit Price':'float'}, temp=False)
                                                                      


conn.commit()
conn.close()
end = time.time()
delta = end - start
print("took %.2f seconds to process" % delta)
print("Update Completed")
# print(df['Reporting_Date'].unique())
print('Last File Uploaded :',max_file)

took 8.44 seconds to process
Update Completed
Last File Uploaded : C:\Users\A803377\Clearon Spend Weekly\Spend Report 3_13_2023.xlsx

In [ ]:
# import pandas as pd
# import sqlalchemy as sa
# import time

# start = time.time()

# connection_string = ("""
# DRIVER={SQL Server Native Client 11.0};
# SERVER= NAAZUREEDWS01;
# UID= svc_tableau_dev;
# PWD= EwSol@321$;
# DATABASE=TableauDB;
# trusted_connection=Yes""")

# connection_url = sa.engine.URL.create(
#     "mssql+pyodbc", 
#     query=dict(odbc_connect=connection_string)
# )
# engine = sa.create_engine(connection_url, fast_executemany=True)

# df.to_sql('ManualClearonSpendReport1',engine,schema= 'rpt',if_exists= "append", index=False)


# end = time.time()
# delta = end - start
# print("took %.2f seconds to process" % delta)
# print("Update Completed")

In [1]:
# df.columns

In [22]:
# conn.close()

In [2]:
# conn = pyodbc.connect("""
# DRIVER={SQL Server Native Client 11.0};
# SERVER= NAAZUREEDWS01;
# UID= svc_tableau_dev;
# PWD= EwSol@321$;
# DATABASE=TableauDB;
# trusted_connection=Yes""")

# Production Report Weekly

In [12]:
# Reading Path of Latest Excel file 
import glob
import os.path

folder_path = r'C:\Users\A803377\Clearon Production Report'
file_type = r'\*xlsx'
files = glob.glob(folder_path + file_type)
max_file = max(files, key=os.path.getctime)

print(max_file)

C:\Users\A803377\Clearon Production Report\Production Report 3_13_2023.xlsx

In [13]:
from datetime import timedelta

df=pd.read_excel(max_file)

# df= pd.read_excel(r'C:\Users\A803377\Downloads\Production Report 11_21_2022.xlsx',sheet_name=0)
df[['Product Element', 'O-grade','Comments']] = df[['Product Element', 'O-grade','Comments']].astype('string')

# df = df.replace(np.nan, '', regex=True)

df[["Actual","Planned"]] = df[["Actual","Planned"]].replace(' ', 0.0, regex=True)
df[["Actual","Planned"]] = df[["Actual","Planned"]].replace('-', 0.0, regex=True)

df[["Actual","Planned"]] = df[["Actual","Planned"]].astype("float64")
# df[["Actual","Planned"]] = df[["Actual","Planned"]].str.replace(' ', '').astype(float)
df["Actual"] = df["Actual"].replace(' ', 0.0, regex=True)

df['Reporting_Date'] = ((pd.Timestamp.today()- timedelta(days=1)).strftime('%Y-%m-%d')) 
df['Reporting_Date'] =  pd.to_datetime(df['Reporting_Date'], format='%Y-%m-%d')

df = df.replace(np.nan, '', regex=True)

df

,Product Element,Date,Actual,Planned,O-grade,Comments,Reporting_Date
0,CDB-90,2023-03-01,83790.0,99225.0,6615,Inventory Control,2023-03-13
1,CDB-90,2023-03-02,11025.0,145530.0,-,Inventory Control,2023-03-13
2,CDB-90,2023-03-03,0.0,145530.0,-,Inventory Control,2023-03-13
3,CDB-90,2023-03-04,0.0,145530.0,-,Inventory Control,2023-03-13
4,CDB-90,2023-03-05,0.0,145530.0,-,Inventory Control,2023-03-13
5,CDB-90,2023-03-06,0.0,145530.0,-,Down/Inventory Control,2023-03-13
6,CDB-90,2023-03-07,0.0,77175.0,-,Down/Inventory Control,2023-03-13
7,CDB-90,2023-03-08,0.0,61740.0,-,Down/Inventory Control,2023-03-13
8,CDB-90,2023-03-09,0.0,145530.0,-,Down/Inventory Control,2023-03-13
9,CDB-90,2023-03-10,0.0,145530.0,-,,2023-03-13
10,CDB-90,2023-03-11,0.0,145530.0,-,,2023-03-13
11,CDB-90,2023-03-12,0.0,145530.0,-,,2023-03-13
12,CDB-90,2023-03-13,0.0,145530.0,,,2023-03-13
13,CDB-90,2023-03-14,0.0,145530.0,,,2023-03-13
14,CDB-90,2023-03-15,0.0,99225.0,,,2023-03-13
15,CDB-90,2023-03-16,0.0,145530.0,,,2023-03-13
16,CDB-90,2023-03-17,0.0,145530.0,,,2023-03-13
17,CDB-90,2023-03-18,0.0,145530.0,,,2023-03-13
18,CDB-90,2023-03-19,0.0,145530.0,,,2023-03-13
19,CDB-90,2023-03-20,0.0,145530.0,,,2023-03-13
20,CDB-90,2023-03-21,0.0,77175.0,,,2023-03-13
21,CDB-90,2023-03-22,0.0,61740.0,,,2023-03-13
22,CDB-90,2023-03-23,0.0,145530.0,,,2023-03-13
23,CDB-90,2023-03-24,0.0,145530.0,,,2023-03-13
24,CDB-90,2023-03-25,0.0,145530.0,,,2023-03-13
25,CDB-90,2023-03-26,0.0,145530.0,,,2023-03-13
26,CDB-90,2023-03-27,0.0,145530.0,,,2023-03-13
27,CDB-90,2023-03-28,0.0,145530.0,,,2023-03-13
28,CDB-90,2023-03-29,0.0,99225.0,,,2023-03-13
29,CDB-90,2023-03-30,0.0,145530.0,,,2023-03-13
30,CDB-90,2023-03-31,0.0,145530.0,,,2023-03-13
31,CDB-56,2023-03-01,0.0,74970.0,-,Down/Inventory Control,2023-03-13
32,CDB-56,2023-03-02,0.0,74970.0,-,Down/Inventory Control,2023-03-13
33,CDB-56,2023-03-03,0.0,74970.0,-,Down/Inventory Control,2023-03-13
34,CDB-56,2023-03-04,0.0,74970.0,-,Down/Inventory Control,2023-03-13
35,CDB-56,2023-03-05,0.0,74970.0,-,Down/Inventory Control,2023-03-13
36,CDB-56,2023-03-06,0.0,74970.0,-,Down/Inventory Control,2023-03-13
37,CDB-56,2023-03-07,0.0,74970.0,-,Down/Inventory Control,2023-03-13
38,CDB-56,2023-03-08,0.0,74970.0,-,Down/Inventory Control,2023-03-13
39,CDB-56,2023-03-09,0.0,74970.0,-,Down/Inventory Control,2023-03-13
40,CDB-56,2023-03-10,0.0,74970.0,-,,2023-03-13
41,CDB-56,2023-03-11,0.0,74970.0,-,,2023-03-13
42,CDB-56,2023-03-12,0.0,74970.0,-,,2023-03-13
43,CDB-56,2023-03-13,0.0,74970.0,,,2023-03-13
44,CDB-56,2023-03-14,0.0,74970.0,,,2023-03-13
45,CDB-56,2023-03-15,0.0,74970.0,,,2023-03-13
46,CDB-56,2023-03-16,0.0,74970.0,,,2023-03-13
47,CDB-56,2023-03-17,0.0,74970.0,,,2023-03-13
48,CDB-56,2023-03-18,0.0,74970.0,,,2023-03-13
49,CDB-56,2023-03-19,0.0,74970.0,,,2023-03-13
50,CDB-56,2023-03-20,0.0,74970.0,,,2023-03-13
51,CDB-56,2023-03-21,0.0,74970.0,,,2023-03-13
52,CDB-56,2023-03-22,0.0,74970.0,,,2023-03-13
53,CDB-56,2023-03-23,0.0,74970.0,,,2023-03-13
54,CDB-56,2023-03-24,0.0,74970.0,,,2023-03-13
55,CDB-56,2023-03-25,0.0,74970.0,,,2023-03-13
56,CDB-56,2023-03-26,0.0,74970.0,,,2023-03-13
57,CDB-56,2023-03-27,0.0,74970.0,,,2023-03-13
58,CDB-56,2023-03-28,0.0,74970.0,,,2023-03-13
59,CDB-56,2023-03-29,0.0,74970.0,,,2023-03-13
60,CDB-56,2023-03-30,0.0,74970.0,,,2023-03-13
61,CDB-56,2023-03-31,0.0,74970.0,,,2023-03-13
62,Pure CA,2023-03-01,27909.0,80000.0,-,Inventory Control,2023-03-13
63,Pure CA,2023-03-02,3200.0,80000.0,-,Inventory Control,2023-03-13
64,Pure CA,2023-03-03,0.0,80000.0,-,Inventory Control,2023-03-13
65,Pure CA,2023-03-04,0.0,60000.0,-,Inventory Control,2023-03-13
66,Pure CA,2023-03-05,0.0,0.0,-,Inventory Control,2023-03-13
67,Pure CA,2023-03-06,0.0,0.0,-,Down/Inventory Control,2023-03-13
68,Pure CA,2023-03-07,0.0,0.0,-,Down/Inventory Control,2023-03-13
69,Pure CA,2023-03-08,0.0,0.0,-,Down/Inventory Control,2023-03-13
70,Pure CA,2023-03-09,0.0,0.0,-,Down/Inventory Control,2023-03-13
71,Pure CA,2023-03-10,0.0,0.0,-,0,2023-03-13
72,Pure CA,2023-03-11,0.0,0.0,-,0,2023-03-13
73,Pure CA,2023-03-12,0.0,0.0,-,0,2023-03-13
74,Pure CA,2023-03-13,0.0,0.0,,,2023-03-13
75,Pure CA,2023-03-14,0.0,0.0,,,2023-03-13
76,Pure CA,2023-03-15,0.0,30000.0,,,2023-03-13
77,Pure CA,2023-03-16,0.0,80000.0,,,2023-03-13
78,Pure CA,2023-03-17,0.0,80000.0,,,2023-03-13
79,Pure CA,2023-03-18,0.0,80000.0,,,2023-03-13
80,Pure CA,2023-03-19,0.0,80000.0,,,2023-03-13
81,Pure CA,2023-03-20,0.0,80000.0,,,2023-03-13
82,Pure CA,2023-03-21,0.0,80000.0,,,2023-03-13
83,Pure CA,2023-03-22,0.0,80000.0,,,2023-03-13
84,Pure CA,2023-03-23,0.0,80000.0,,,2023-03-13
85,Pure CA,2023-03-24,0.0,80000.0,,,2023-03-13
86,Pure CA,2023-03-25,0.0,80000.0,,,2023-03-13
87,Pure CA,2023-03-26,0.0,80000.0,,,2023-03-13
88,Pure CA,2023-03-27,0.0,80000.0,,,2023-03-13
89,Pure CA,2023-03-28,0.0,80000.0,,,2023-03-13
90,Pure CA,2023-03-29,0.0,80000.0,,,2023-03-13
91,Pure CA,2023-03-30,0.0,80000.0,,,2023-03-13
92,Pure CA,2023-03-31,0.0,80000.0,,,2023-03-13

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product Element  93 non-null     string
 1   Date             93 non-null     datetime64[ns]
 2   Actual           93 non-null     float64
 3   Planned          93 non-null     float64
 4   O-grade          93 non-null     string
 5   Comments         93 non-null     string
 6   Reporting_Date   93 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(2), string(3)
memory usage: 5.2 KB

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product Element  84 non-null     string
 1   Date             84 non-null     datetime64[ns]
 2   Actual           84 non-null     float64
 3   Planned          84 non-null     float64
 4   O-grade          84 non-null     string
 5   Comments         84 non-null     string
 6   Reporting_Date   84 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(2), string(3)
memory usage: 4.7 KB

In [14]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import urllib
import sqlalchemy as sa
import pyodbc
import time
from fast_to_sql import fast_to_sql as fts

start = time.time()
#Connecting to SQL 
conn = pyodbc.connect("""
DRIVER={SQL Server Native Client 11.0};
SERVER= NAAZUREEDWS01;
UID= svc_tableau_dev;
PWD= EwSol@321$;
DATABASE=TableauDB;
trusted_connection=Yes""")

fts.fast_to_sql(df,'rpt.ManualClearonProductionReport_Weekly',conn, if_exists="append", custom={'Product Element':'nvarchar(225)','Actual':'float(53)',
                                                                                               'Planned':'float(53)','O-grade':'nvarchar(225)',
                                                                                               'Comments':'nvarchar(225)'}, temp=False)

conn.commit()
conn.close()
end = time.time()
delta = end - start
print("took %.2f seconds to process" % delta)
print("Update Completed")
print(df['[Reporting_Date]'].unique())
print('Last File Uploaded :',max_file)

took 4.08 seconds to process
Update Completed
['2023-03-13T00:00:00.000000000']
Last File Uploaded : C:\Users\A803377\Clearon Production Report\Production Report 3_13_2023.xlsx

In [ ]:
cnx = mysql.connector.connect(database='world')
cursor = cnx.cursor(dictionary=True)
cursor.execute("SELECT * FROM country WHERE Continent = 'Europe'")

print("Countries in Europe:")
for row in cursor:
    print("* {Name}".format(Name=row['Name']))

In [6]:
import pyodbc 
cnxn = pyodbc.connect("Driver={SQL Server Native Client 11.0};"
                        "Server=NAAZUREEDWS01;"
                        "Database=TableauDB;"
                        "uid=svc_tableau_dev;pwd=EwSol@321$;"
                        "Trusted_Connection=yes;")


# cursor = cnxn.cursor()
# cursor.execute('select Max([Reporting_Date] ) from TableauDB.[rpt].[ManualClearonDailySales]')


df_1 = pd.read_sql_query('select Max([Reporting_Date] ) as [Reporting_Date] from TableauDB.[rpt].[ManualClearonDailySales]', cnxn)

print(df_1)
# for i in cursor:
#     print(i)
    
cnxn.close()

  Reporting_Date
0     2023-02-20

In [68]:
cnxn.close()

In [7]:
dict = df.columns.to_dict('dict')

AttributeError: 'Index' object has no attribute 'to_dict'

In [15]:
my_dict = { df.columns[i]: 'nvarchar(225)' for i in range(len(df.columns))}

In [12]:
df.columns[0]

'Product Element'

In [16]:
my_dict

{'Product Element': 'nvarchar(225)',
 'Date': 'nvarchar(225)',
 'Actual': 'nvarchar(225)',
 'Planned': 'nvarchar(225)',
 'O-grade': 'nvarchar(225)',
 'Comments': 'nvarchar(225)',
 'Reporting_Date': 'nvarchar(225)'}

In [51]:
my_dict =  {df.columns[i]: 'nvarchar(225)'  if df.dtypes[i].name == 'string' else df.columns[i]: 'float' for i in range(len(df.columns))}

SyntaxError: invalid syntax (Temp/ipykernel_29160/3318024522.py, line 1)

In [49]:
range(len(df.columns)-2)

range(0, 5)

In [29]:
df.columns[0].dtype

AttributeError: 'str' object has no attribute 'dtype'

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product Element  90 non-null     string
 1   Date             90 non-null     datetime64[ns]
 2   Actual           90 non-null     float64
 3   Planned          90 non-null     float64
 4   O-grade          90 non-null     string
 5   Comments         90 non-null     string
 6   Reporting_Date   90 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(2), string(3)
memory usage: 5.0 KB

In [27]:
type('Product Element')

str

In [31]:
['Product Element'].dtype()

AttributeError: 'list' object has no attribute 'dtype'

In [38]:
df.columns[1].dtype

AttributeError: 'list' object has no attribute 'dtype'

In [44]:
df.dtypes[1].name

'datetime64[ns]'