In [13]:
import pyodbc
cnxn = pyodbc.connect('Driver=SQL Server;Server=NAAZUREEDWS01;Database=TableauDB;Trusted_Connection=yes;')
#cursor = cnxn.cursor()
#cursor.execute("SELECT top 10 * FROM dbo.financemaster")

In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

In [3]:
data = pd.read_sql_query("select top 10 * from [LIB_EDW_RTP].[dbo].[ZZZ_PAID_ON_TIME_INVOICES] ORDER BY [Posting Date] DESC", cnxn)

In [4]:
data

,DATA_EXTRACT_DATE,Client,Fiscal Year,Company,Accounting Document,Accounting Document Line,Posting Date,Document Date,Clearing Date,Clearing Date Text,...,Cash Disc Days1,Cash Disc Days2,Cash Disc Percent1,Cash Disc Percent2,Cash Discount Amount,Vendor Account Group,Payment Supplement Method,Critical Vendor,Potential Amount,Debit/Credit Indicator
0,2022-02-01,020,2022,0612,5100026806,001,2022-01-31,2021-12-13,2022-02-01,20220201,...,30.0,0.0,0.0,0.0,0.0,ZPAY,None,Non Critical Vendor,0.0,H
1,2022-02-01,020,2022,0612,5100026804,001,2022-01-31,2021-12-20,2022-02-01,20220201,...,30.0,0.0,0.0,0.0,0.0,ZPAY,None,Non Critical Vendor,0.0,H
2,2022-02-01,020,2022,0612,5100026807,001,2022-01-31,2021-12-09,2022-02-01,20220201,...,30.0,0.0,0.0,0.0,0.0,ZPAY,None,Non Critical Vendor,0.0,H
3,2022-02-01,020,2022,0612,5100026784,001,2022-01-31,2022-01-01,2022-02-01,20220201,...,30.0,0.0,0.0,0.0,0.0,ZPAY,None,Non Critical Vendor,0.0,H
4,2022-02-01,020,2022,0612,5100026785,001,2022-01-31,2022-01-01,2022-02-01,20220201,...,20.0,0.0,0.0,0.0,0.0,ZPAY,None,Non Critical Vendor,0.0,H
5,2022-02-01,020,2022,0612,5100026805,001,2022-01-31,2021-12-15,2022-02-01,20220201,...,30.0,0.0,0.0,0.0,0.0,ZPAY,None,Non Critical Vendor,0.0,H
6,2022-02-01,020,2022,0612,5100026781,001,2022-01-31,2021-12-29,2022-02-01,20220201,...,30.0,0.0,0.0,0.0,0.0,ZPAY,None,Non Critical Vendor,0.0,H
7,2022-02-01,020,2022,0612,5100026782,001,2022-01-31,2021-12-31,2022-02-01,20220201,...,0.0,0.0,0.0,0.0,0.0,ZPAY,None,Non Critical Vendor,0.0,H
8,2022-02-01,020,2022,0612,5100026803,001,2022-01-31,2021-12-24,2022-02-01,20220201,...,30.0,0.0,0.0,0.0,0.0,ZPAY,None,Non Critical Vendor,0.0,H
9,2022-02-01,020,2022,0612,5100026777,001,2022-01-31,2021-12-15,2022-02-01,20220201,...,0.0,0.0,0.0,0.0,0.0,ZPAY,None,Non Critical Vendor,0.0,H

In [55]:
data1 = pd.read_sql_query("select top 1000 * from [LIB_EDW_RTP].[dbo].[ZZZ_INVOICES_RECORDED] ORDER BY [Posting Date] DESC", cnxn)

In [56]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 50 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   DATA_EXTRACT_DATE                   1000 non-null   object
 1   Client                              1000 non-null   object
 2   Fiscal Year                         1000 non-null   object
 3   Company                             1000 non-null   object
 4   Accounting Document                 1000 non-null   object
 5   Accounting Document Line            1000 non-null   object
 6   Posting Date                        1000 non-null   object
 7   Document Date                       1000 non-null   object
 8   Clearing Date                       0 non-null      object
 9   Clearing Date Text                  1000 non-null   object
 10  Vendor                              1000 non-null   object
 11  Special GL Indicator                1000 non-null   object
 12  Document Type                       1000 non-null   object
 13  Master Reconciliation Account Key   1000 non-null   object
 14  Master Reconciliation Account       1000 non-null   object
 15  Posting Reconciliation Account Key  1000 non-null   object
 16  Posting Reconciliation Account      1000 non-null   object
 17  Purchasing Document Number          1000 non-null   object
 18  Item Text                           1000 non-null   object
 19  Reference Document Number           1000 non-null   object
 20  Payment Block                       1000 non-null   object
 21  Payment Terms                       1000 non-null   object
 22  Clearing Document Number            1000 non-null   object
 23  Payment Method                      1000 non-null   object
 24  Assignment Number                   1000 non-null   object
 25  Posting Key                         1000 non-null   object
 26  Source Table                        1000 non-null   object
 27  Controlling Area                    1000 non-null   object
 28  Profit Center Key                   1000 non-null   object
 29  Due Date                            1000 non-null   object
 30  User Id                             1000 non-null   object
 31  Chart of Accounts                   1000 non-null   object
 32  Group Currency                      1000 non-null   object
 33  Group Currency Amount               1000 non-null   float64
 34  Company Currency                    1000 non-null   object
 35  Company Currency Amount             1000 non-null   float64
 36  Document Currency                   1000 non-null   object
 37  Document Currency Amount            1000 non-null   float64
 38  Transaction Type                    1000 non-null   object
 39  Vendor Company Key                  1000 non-null   object
 40  Entry Date                          1000 non-null   object
 41  RKPF Reference Key                  1000 non-null   object
 42  Tax on Sales                        1000 non-null   object
 43  Country Key                         1000 non-null   object
 44  Vendor Name                         1000 non-null   object
 45  Vendor Account Group                1000 non-null   object
 46  Payment Supplement Method           240 non-null    object
 47  Critical Vendor                     1000 non-null   object
 48  Baseline Date                       1000 non-null   object
 49  Debit/Credit Indicator              1000 non-null   object
dtypes: float64(3), object(47)
memory usage: 390.8+ KB

In [67]:
d9['Due Date']= pd.to_datetime(d9['Due Date'])
d9['DATA_EXTRACT_DATE']= pd.to_datetime(d9['DATA_EXTRACT_DATE'])

C:\Users\A803377\AppData\Local\Temp/ipykernel_14008/2543354696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d9['Due Date']= pd.to_datetime(d9['Due Date'])
C:\Users\A803377\AppData\Local\Temp/ipykernel_14008/2543354696.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d9['DATA_EXTRACT_DATE']= pd.to_datetime(d9['DATA_EXTRACT_DATE'])

In [68]:
d9.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 857 entries, 0 to 999
Data columns (total 50 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   DATA_EXTRACT_DATE                   857 non-null    datetime64[ns]
 1   Client                              857 non-null    object
 2   Fiscal Year                         857 non-null    object
 3   Company                             857 non-null    object
 4   Accounting Document                 857 non-null    object
 5   Accounting Document Line            857 non-null    object
 6   Posting Date                        857 non-null    object
 7   Document Date                       857 non-null    object
 8   Clearing Date                       0 non-null      object
 9   Clearing Date Text                  857 non-null    object
 10  Vendor                              857 non-null    object
 11  Special GL Indicator                857 non-null    object
 12  Document Type                       857 non-null    object
 13  Master Reconciliation Account Key   857 non-null    object
 14  Master Reconciliation Account       857 non-null    object
 15  Posting Reconciliation Account Key  857 non-null    object
 16  Posting Reconciliation Account      857 non-null    object
 17  Purchasing Document Number          857 non-null    object
 18  Item Text                           857 non-null    object
 19  Reference Document Number           857 non-null    object
 20  Payment Block                       857 non-null    object
 21  Payment Terms                       857 non-null    object
 22  Clearing Document Number            857 non-null    object
 23  Payment Method                      857 non-null    object
 24  Assignment Number                   857 non-null    object
 25  Posting Key                         857 non-null    object
 26  Source Table                        857 non-null    object
 27  Controlling Area                    857 non-null    object
 28  Profit Center Key                   857 non-null    object
 29  Due Date                            857 non-null    datetime64[ns]
 30  User Id                             857 non-null    object
 31  Chart of Accounts                   857 non-null    object
 32  Group Currency                      857 non-null    object
 33  Group Currency Amount               857 non-null    float64
 34  Company Currency                    857 non-null    object
 35  Company Currency Amount             857 non-null    float64
 36  Document Currency                   857 non-null    object
 37  Document Currency Amount            857 non-null    float64
 38  Transaction Type                    857 non-null    object
 39  Vendor Company Key                  857 non-null    object
 40  Entry Date                          857 non-null    object
 41  RKPF Reference Key                  857 non-null    object
 42  Tax on Sales                        857 non-null    object
 43  Country Key                         857 non-null    object
 44  Vendor Name                         857 non-null    object
 45  Vendor Account Group                857 non-null    object
 46  Payment Supplement Method           211 non-null    object
 47  Critical Vendor                     857 non-null    object
 48  Baseline Date                       857 non-null    object
 49  Debit/Credit Indicator              857 non-null    object
dtypes: datetime64[ns](2), float64(3), object(45)
memory usage: 341.5+ KB

In [ ]:
[ZZZ_INVOICES_RECORDED]

In [57]:
date = data1.groupby('DATA_EXTRACT_DATE')

In [59]:
d9= date.get_group('2022-01-19')

In [61]:
d9.sum(axis = 1, skipna = True)
d9['Group Currency Amount'].sum()

C:\Users\A803377\AppData\Local\Temp/ipykernel_14008/588268988.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  d9.sum(axis = 1, skipna = True)

-8477933.186843

In [73]:
df=pd.DataFrame()

In [74]:
df['Difference'] = d9['Due Date']-d9['DATA_EXTRACT_DATE']

In [76]:
d9['Due Date']

0     2022-01-11
1     2022-01-07
2     2022-01-14
3     2021-12-31
4     2021-11-10
         ...
995   2022-02-28
996   2022-02-12
997   2022-01-29
998   2022-04-16
999   2022-04-14
Name: Due Date, Length: 857, dtype: datetime64[ns]

In [77]:
d9['DATA_EXTRACT_DATE']

0     2022-01-19
1     2022-01-19
2     2022-01-19
3     2022-01-19
4     2022-01-19
         ...
995   2022-01-19
996   2022-01-19
997   2022-01-19
998   2022-01-19
999   2022-01-19
Name: DATA_EXTRACT_DATE, Length: 857, dtype: datetime64[ns]

In [75]:
df

    Difference
0      -8 days
1     -12 days
2      -5 days
3     -19 days
4     -70 days
..         ...
995    40 days
996    24 days
997    10 days
998    87 days
999    85 days

[857 rows x 1 columns]

In [ ]:
IF [Invoice aging]<=0 THEN 'Due'
ELSEIF [Invoice aging]>0 THEN 'Not due'
END

In [3]:
data10 = pd.read_sql_query("select top 30000* from [LIB_EDW_RTP].[dbo].[ZZZ_INVOICES_RECORDED] WHERE [Fiscal Year]>=2021 ORDER BY [Posting Date] DESC", cnxn)

In [4]:
data10

,DATA_EXTRACT_DATE,Client,Fiscal Year,Company,Accounting Document,Accounting Document Line,Posting Date,Document Date,Clearing Date,Clearing Date Text,...,Entry Date,RKPF Reference Key,Tax on Sales,Country Key,Vendor Name,Vendor Account Group,Payment Supplement Method,Critical Vendor,Baseline Date,Debit/Credit Indicator
0,2022-01-20,020,2022,0410,5100455757,001,2022-01-20,2022-01-12,None,00000000,...,2022-01-20,51123041422022,G0,DE,BASF SE,ZPAY,None,Non Critical Vendor,2022-01-12,H
1,2022-01-20,020,2022,1800,5100074450,001,2022-01-20,2022-01-12,None,00000000,...,2022-01-20,51123042522022,V2,MX,ALBERTO BETANZOS AGUIRRE,ZPAY,None,Non Critical Vendor,2022-01-12,H
2,2022-01-20,020,2022,0911,5100025442,001,2022-01-20,2022-01-07,None,00000000,...,2022-01-20,51123040192022,PA,IN,PETRO CHEM INDUSTRIES,ZPAY,None,Non Critical Vendor,2022-01-07,H
3,2022-01-20,020,2022,0612,5100026477,001,2022-01-20,2022-01-14,None,00000000,...,2022-01-20,51123037862022,**,AU,COOGEE QCA PTY LTD,ZPAY,None,Non Critical Vendor,2022-02-28,H
4,2022-01-20,020,2022,0869,5100186492,001,2022-01-20,2021-11-18,None,00000000,...,2022-01-20,51123039922022,JU,CN,CHINA CUSTOMS,ZTAX,None,Non Critical Vendor,2021-11-18,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,2022-01-15,020,2022,1020,5101030724,001,2022-01-11,2021-12-23,None,00000000,...,2022-01-11,51122958402022,NT,CA,AQUATOX TESTING AND CONSULTING INC,ZPAY,None,Non Critical Vendor,2021-12-23,H
29996,2022-01-15,020,2022,1020,5101030739,001,2022-01-11,2022-01-04,None,00000000,...,2022-01-11,51122959512022,NT,US,JUNGBUNZLAUER INC,ZPAY,None,Non Critical Vendor,2022-01-04,H
29997,2022-01-15,020,2022,0900,5100004171,001,2022-01-11,2021-12-30,None,00000000,...,2022-01-11,51122956362022,U6,TR,BDP INTERNATIONAL LOJISTIK LIMITED,ZPAY,88,Critical Vendor,2021-12-30,H
29998,2022-01-15,020,2022,0900,5100004176,001,2022-01-11,2021-12-31,None,00000000,...,2022-01-11,51122957192022,**,TR,VENTUR GUMRUK MUSAVIRLIGI VE,ZPAY,None,Non Critical Vendor,2021-12-31,H
29999,2022-01-15,020,2022,5500,5100143178,001,2022-01-11,2021-12-28,None,00000000,...,2022-01-11,51122959642022,IH,BR,MARIMEX DESP TRANSP E SERV LTDA,ZPAY,None,Non Critical Vendor,2021-12-28,H

In [87]:
data10.sum(axis = 1, skipna = True)
data10['Group Currency Amount'].sum()

-220298232.97459403

In [5]:
data10 = pd.read_sql_query("select top 100 * from [TableauDB].[rpt].[Vw_OpenOrdersDailyReport] ", cnxn)

DatabaseError: Execution failed on sql 'select top 100 * from [TableauDB].[rpt].[Vw_OpenOrdersDailyReport] ': ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]The SELECT permission was denied on the object 'Reporting Exchange Rate Euro', database 'EDWDBReport', schema 'rpt'. (229) (SQLExecDirectW)")

In [10]:
data10

,DATA_EXTRACT_DATE,Client,Fiscal Year,Company,Accounting Document,Accounting Document Line,Posting Date,Document Date,Clearing Date,Clearing Date Text,...,Entry Date,RKPF Reference Key,Tax on Sales,Country Key,Vendor Name,Vendor Account Group,Payment Supplement Method,Critical Vendor,Baseline Date,Debit/Credit Indicator
0,2022-01-20,020,2022,0410,5100455739,001,2022-01-20,2022-01-18,None,00000000,...,2022-01-20,51123040512022,9V,DE,LEXZAU SCHARBAU GMBH UND CO KG,ZPAY,None,Non Critical Vendor,2022-01-18,H
1,2022-01-20,020,2022,0410,5100455748,001,2022-01-20,2022-01-11,None,00000000,...,2022-01-20,51123038082022,G0,DE,BASF SE,ZPAY,None,Non Critical Vendor,2022-01-11,H
2,2022-01-20,020,2022,1800,5100074436,001,2022-01-20,2022-01-14,None,00000000,...,2022-01-20,51123040832022,V2,MX,NOPCHEM S A DE C V,ZPAY,None,Non Critical Vendor,2022-01-14,H
3,2022-01-20,020,2022,1800,5100074448,001,2022-01-20,2021-12-21,None,00000000,...,2022-01-20,51123042412022,**,MX,TRANSPORTES JORGE ANCER SA DE CV,ZPAY,None,Non Critical Vendor,2021-12-21,H
4,2022-01-20,020,2022,0410,5100455750,001,2022-01-20,2022-01-08,None,00000000,...,2022-01-20,51123038102022,G0,DE,BASF SE,ZPAY,None,Non Critical Vendor,2022-01-08,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2022-01-16,020,2022,0494,1900020186,001,2022-01-04,2022-01-17,None,00000000,...,2022-01-04,190002018604942022,**,DE,LEASEPLAN DEUTSCHLAND GMBH,ZPAY,88,Critical Vendor,2022-01-17,H
99996,2022-01-16,020,2022,7863,5100022353,001,2022-01-04,2021-12-09,None,00000000,...,2022-01-04,51122886672022,YH,CN,SHANGHAI HUILAIKANG CHEMICAL CO LTD,ZPAY,None,Non Critical Vendor,2021-12-09,H
99997,2022-01-09,020,2022,0612,5100026037,001,2022-01-04,2021-12-19,None,00000000,...,2022-01-04,51122884642022,**,AU,DGL WAREHOUSING AND DISTRIBUTION,ZPAY,None,Non Critical Vendor,2021-12-19,H
99998,2022-01-10,020,2022,0410,2800049607,001,2022-01-04,2022-01-04,None,00000000,...,2022-01-04,51122891452022,9V,NL,KLG EUROPE VENLO BV,ZPAY,None,Non Critical Vendor,2022-02-03,H
99999,2022-01-10,020,2022,0410,2800049681,001,2022-01-04,2021-12-31,None,00000000,...,2022-01-04,51122892192022,9V,IT,LOTRANS AUTOTRASPORTI SRL,ZPAY,88,Critical Vendor,2022-03-01,H

In [9]:
num = pd.read_sql_query("select -(SUM([Group Currency Amount])) from [LIB_EDW_RTP].[dbo].[ZZZ_INVOICES_RECORDED] as Value WHERE [DATA_EXTRACT_DATE]>='2022-1-2' ", cnxn)

In [ ]:
SELECT SUM(Quantity) AS TotalItemsOrdered FROM OrderDetails

In [10]:
num

0  7.291770e+09

In [ ]:
SELECT
DATA_EXTRACT_DATE
,ZZZ.Client
,[Fiscal Year]
,ZZZ.Company
,[Accounting Document]
,[Accounting Document Line]
,[Posting Date]
,[Document Date]
,[Clearing Date]
,[Clearing Date Text]
,[Baseline Date]
,ZZZ.Vendor
,[Special GL Indicator]
,[Document Type]
,[Master Reconciliation Account Key]
,[Master Reconciliation Account]
,[Posting Reconciliation Account Key]
,[Posting Reconciliation Account]
,[Purchasing Document Number]
,[Item Text]
,[Reference Document Number]
,[Payment Block]
,[Payment Terms]
,[Clearing Document Number]
,[Payment Method]
,[Assignment Number]
,[Posting Key]
,[Source Table]
,ZZZ.[Controlling Area]
,[Profit Center Key]
,[Due Date]
,[User Id]
,ZZZ.[Chart of Accounts]
,[Group Currency]
,[Group Currency Amount]
,[Company Currency]
,[Company Currency Amount]
,[Document Currency]
,[Document Currency Amount]
,[Transaction Type]
,[Vendor Company Key]
,[Entry Date]
,[RKPF Reference Key]
,[Tax on Sales]
,[Country Key]
,ZZZ.[Vendor Account Group]
,ZZZ.[Payment Supplement Method]
,ZZZ.[Critical Vendor]
,ZZZ.[Vendor Name]
,C.[Company Name]
,C.City
,C.Country
,C.Currency
,C.[Global Region]
,V.[Display Vendor]
,ZZZ.[Debit/Credit Indicator]
,EX.[BP FX RATE]
,EX.FromCurrency FROM LIB_EDW_RTP.dbo.ZZZ_INVOICES_RECORDED ZZZ
LEFT OUTER JOIN LIB_EDW_RTP.dim.Company C
ON ZZZ.Client = C.Client
AND ZZZ.Company = C.Company
AND ZZZ.[Chart of Accounts] = C.[Chart Of Accounts]
AND ZZZ.[Controlling Area] = C.[Controlling Area]
LEFT OUTER JOIN LIB_EDW_RTP.dim.Vendor V
ON ZZZ.Client = V.Client
AND ZZZ.Vendor = V.Vendor left join LIB_EDW_RTP.[RPT].[Reporting Exchange Rate] EX
ON EX.FromCurrency=[Document Currency]
and EX.[Fiscal Year Number] =[Fiscal Year]
And case when len(cast(EX.[Calendar Month Number] as nvarchar))=2
then EX.[Calendar Month Number]
else concat(0,EX.[Calendar Month Number])
end =substring(cast(ZZZ.[Posting Date] as nvarchar),6,2)

In [1]:
5589085 + 2825997

8415082